version: '3.8'

services:
  foo:
    build:
      context: nginx
      dockerfile: Containerfile
    environment:
      - DB_TYPE=postgres
      - DB_HOST=db:5432
      - DB_NAME=foo
      - DB_USER=foo
      - DB_PASSWD=foo
    restart: always
    ports:
      - 5000:80
      - 5443:443
    expose:
      - 80
      - 443
    depends_on:
      - app
  app:
    build:
      context: ./app
      dockerfile: Containerfile
    ports:
      - 5001:3000
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/myapp
      - NODE_ENV=production
      - SKIP_ENV_VALIDATION=true
    depends_on:
      - db
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=myapp
    volumes:
      - postgres_data:/var/lib/postgresql/data:Z
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
